# Site settings
title: Mi Blog Técnico
email: jasmedia.jas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My tech blog (Mi Blog Técnico), related with coding, embedded systems, new technologies, various product design concept, etc. All these notes are written based on my limited knowledge in various technologies and concepts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jasmedia
github_username:  jaseemkp

# Build settings
markdown: kramdown
